name: geodesy
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=3.8.0 <4.0.0'


dependencies:
  # audio_session: ^0.2.2
  audio_service: ^0.18.18
  camera: ^0.11.0
  cubixd: ^0.1.1
  flutter:
    sdk: flutter
  flutter_compass: ^0.8.1
  geolocator: ^14.0.2
  image: ^4.0.0
  latlng: ^2.0.7
  motion_core: ^0.0.5
  opencv_dart: ^1.4.3
  permission_handler: ^12.0.1
  vector_math: ^2.1.4


dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/calibration_data.json
